# Generated by Django 4.1.4 on 2022-12-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="solved",
            field=models.BooleanField(default=False),
        ),
    ]
