# Generated by Django 4.1.4 on 2022-12-29 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_project_solved"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="level",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
