# Generated by Django 4.1.4 on 2022-12-29 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_skill_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(related_name="skills", to="mysite.skill"),
        ),
        migrations.CreateModel(
            name="SpecificSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("description", models.TextField()),
                (
                    "related_skill",
                    models.ManyToManyField(
                        related_name="related_skills", to="mysite.skill"
                    ),
                ),
            ],
        ),
    ]
