# Generated by Django 4.1.4 on 2023-01-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0007_skill_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_url",
            field=models.CharField(default="", max_length=250),
        ),
    ]
